# Generated by Django 5.0 on 2023-12-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='reorder_level',
        ),
    ]
